_homepage:
    path:     /
    defaults: { _controller: ChrAlphaBundle:Homepage:index }


browse:
    path: /browse/hair/{hairtype}
    defaults: {_controller: ChrAlphaBundle:Browse:index }

browsebyinch:
    path: /browse/hair/{hairtype}/{inch}
    defaults: {_controller: ChrAlphaBundle:Browse:byinch }

browsebyinchandstyle:
    path: /browse/hair/{hairtype}/{inch}/{style}
    defaults: {_controller: ChrAlphaBundle:Browse:byinchandstyle }

topratedhair:
    path: /shop/hair/topratedhair/{hairtype}
    defaults: {_controller: ChrAlphaBundle:Browse:topratedhair }

overviewfeatured:
    path: /admin/overview
    defaults: {_controller: ChrAlphaBundle:Featured:overview }

viewfeatured:
    path: /admin/viewfeatured/{hairtype}/{inch}/{style}
    defaults: {_controller: ChrAlphaBundle:Featured:index }

createfeatured:
    path: /admin/addfeatured/{hairtype}
    defaults: {_controller: ChrAlphaBundle:Featured:add }

viewfeaturedbyinch:
    path: /admin/viewfeatured/{hairtype}/{inch}
    defaults: {_controller: ChrAlphaBundle:Featured:indexbyinch }

viewfeaturedbyinchandstyle:
    path: /admin/viewfeatured/{hairtype}/{inch}/{style}
    defaults: {_controller: ChrAlphaBundle:Featured:indexbyinchandstyle }



